export const STACK_SCREENS={
BOTTOM_TAB : "BOTTOM_TAB",
PROFILE_EDIT : "PROFILE_EDIT",
PROFILE : ":PROFILE",
}
export const BOTTOM_TAB_SCREEN={
HOME : "HOME",
UPLOAD_POST : "UPLOAD_POST",
PROFILE_SELF : "PROFILE_SELF",
}
export  const AUTH_STACK_SCREEN={
LOGIN : "LOGIN",
SIGNUP : "SIGNUP",
FORGOT_PASSWORD : "FORGOT_PASSWORD",
}
export  const PARAM_ROUTE_SCREEM={
    PROFILE : "PROFILE",
}
